package uk.gov.justice.digital.hmpps.personrecord.service.eventlog

enum class CPRLogEvents {
  CPR_RECORD_CREATED,
  CPR_RECORD_UPDATED,
  CPR_UUID_CREATED,
  CPR_RECORD_MERGED,
  CPR_UUID_MERGED,
  CPR_RECLUSTER_RECORD_MERGED,
  CPR_RECLUSTER_UUID_MERGED,
  CPR_RECLUSTER_NEEDS_ATTENTION,
}
