package uk.gov.justice.digital.hmpps.personrecord.model.types

enum class ReligionCode(val description: String, val current: Boolean) {
  ADV("Adventist", false),
  AGNO("Agnostic", true),
  APO("Apostolic", false),
  ATHE("Atheist", true),
  BAHA("Baháʼí", true),
  BAPT("Christian - Baptist", false),
  BLAC("Black Muslim", false),
  BUDD("Buddhist", true),
  CALV("Calvinist", false),
  CCOG("Celestial Church of God", false),
  CE("Christadelphian", false),
  CHJCLDS("Church of Jesus Christ L D S", true),
  CHRODX("Christian - Orthodox", true),
  CHRST("Christian - Other", true),
  CHSC("Church of Christ, Scientist", true),
  CINW("Church In Wales", false),
  COFE("Christian - Anglican (incl. CofE & CinW)", true),
  COFI("Church of Ireland", false),
  COFN("Church of Norway", false),
  COFS("Church of Scotland", false),
  CONG("Congregational", false),
  COPT("Coptic", false),
  CSW("Church of Sweden", false),
  DRU("Druid", false),
  EODX("Dutch Reform Church", false),
  EORTH("Eastern Orthodox", false),
  EPIS("Episcopalian", false),
  ETHO("Ethiopian Orthodox", false),
  EVAN("Evangelical", false),
  GOSP("Gospel", false),
  GROX("Greek Orthodox", false),
  HARE("Hare Krishna", false),
  HIND("Hindu", true),
  HNDHAR("Hindu/Hare Krishna", false),
  HUM("Humanist", true),
  JAIN("Jain", true),
  JEHV("Jehovah's Witness", true),
  JEW("Jewish", true),
  LUTH("Lutheran", false),
  METH("Christian - Methodist", false),
  MORM("Mormon", false),
  MOS("Muslim", true),
  MUSOTH("Muslim - Other", false),
  NIL("No Faith or Belief", true),
  NONC("Non Conformist", false),
  NONP("Non Permitted Religions", false),
  OORTH("Christian - Oriental Orthodox", true),
  ORTH("Orthodox (Greek/Russian)", false),
  OTH("Other Faith or Belief", true),
  PAG("Pagan", true),
  PAGDRU("Pagan/Druid", false),
  PENT("Pentecostal", false),
  PRES("Christian - Presbyterian", false),
  PROT("Protestant", false),
  QUAK("Quaker", true),
  RAST("Rastafari", true),
  RC("Christian - Roman Catholic", true),
  RUSS("Russian Orthodox", false),
  SALV("Salvation Army", false),
  SATN("Satanist", true),
  SCIE("Scientologist", true),
  SDAY("Seventh Day Adventist", true),
  SHIA("Muslim - Shia", true),
  SHIN("Shintoist", false),
  SHNTAO("Shintoist and Taoist", true),
  SIKH("Sikh", true),
  SPIR("Spiritualist", true),
  SUNI("Muslim - Sunni", false),
  TAO("Taoist", false),
  TPRNTS("They prefer not to say", true),
  UNIF("Unification", false),
  UNIT("Unitarian", false),
  UNKN("Unknown", false),
  UR("United Reformed", false),
  WELS("Welsh Independent", false),
  ZORO("Zoroastrian", true),
}

fun String?.toReligionCodeDescription(): String? = try {
  this?.let { ReligionCode.valueOf(it).description }
} catch (_: Exception) {
  null
}
