package uk.gov.justice.digital.hmpps.personrecord.model.types

enum class ReligionCode(val description: String) {
  AGNO("Agnostic"),
  ATHE("Atheist"),
  BAHA("Baháʼí"),
  BAPT("Christian - Baptist"),
  BUDD("Buddhist"),
  CHRST("Christian - Other"),
  CHRODX("Christian - Orthodox"),
  OORTH("Christian - Oriental Orthodox"),
  CHSC("Church of Christ, Scientist"),
  COFE("Christian - Anglican (incl. CofE & CinW)"),
  CHJCLDS("Church of Jesus Christ L D S"),
  HNDHAR("Hindu/Hare Krishna"),
  HUM("Humanist"),
  JAIN("Jain"),
  JEHV("Jehovah's Witness"),
  JEW("Jewish"),
  METH("Christian - Methodist"),
  MUSOTH("Muslim - Other"),
  SHIA("Muslim - Shia"),
  SUNI("Muslim - Sunni"),
  NIL("No Faith or Belief"),
  OTH("Other Faith or Belief"),
  PAGDRU("Pagan/Druid"),
  PRES("Christian - Presbyterian"),
  QUAK("Quaker"),
  RAST("Rastafari"),
  RC("Christian - Roman Catholic"),
  SATN("Satanist"),
  SCIE("Scientologist"),
  SECULR("Secularism"),
  SDAY("Seventh Day Adventist"),
  SHNTAO("Shintoist and Taoist"),
  SIKH("Sikh"),
  SPIR("Spiritualist"),
  TPRNTS("They prefer not to say"),
  ZORO("Zoroastrian"),
}
