apiVersion: batch/v1
kind: CronJob
metadata:
  name: generate-term-frequencies
spec:
  schedule:  "{{ .Values.cron.generateTermFrequencies }}"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: generate-term-frequencies-job
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --fail --retry 2 -X POST http://localhost:8080/generate/termfrequencies