{{- if .Values.cron.generateDeliusMergeRequestsJob }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "generic-service.fullname" . | trunc 26 }}-generate-delius-merge-requests
spec:
  schedule: "{{ .Values.cron.generateDeliusMergeRequestsJob }}"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 43200
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600 # 4 days
      backoffLimit: 2
      template:
        spec:
          activeDeadlineSeconds: 3600
          restartPolicy: Never
          containers:
            - name: generate-delius-merge-requests-job
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              securityContext:
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
              args:
                - /bin/sh
                - -c
                - curl --fail --retry 2 -X POST http://hmpps-person-record/jobs/service-now/generate-delius-merge-requests
{{- end }}