apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "generic-service.fullname" . | trunc 26 }}-recluster-needs-attention-job
spec:
  schedule:  "{{ .Values.cron.reclusterNeedsAttentionJob }}"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 43200
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600 # 4 days
      backoffLimit: 2
      template:
        spec:
          activeDeadlineSeconds: 3600
          restartPolicy: Never
          containers:
            - name: recluster-needs-attention-job
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              securityContext:
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
              args:
                - /bin/sh
                - -c
                - curl --fail --retry 2 -X POST http://hmpps-person-record/jobs/recluster-needs-attention
