apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "generic-service.fullname" . | trunc 26 }}-record-count-report-job
spec:
  schedule:  "{{ .Values.cron.recordCountReportJob }}"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 43200
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600 # 4 days
      backoffLimit: 2
      template:
        spec:
          activeDeadlineSeconds: 3600
          restartPolicy: Never
          containers:
            - name: record-count-report-job
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --fail --retry 2 -X POST http://hmpps-person-record/jobs/recordcountreport && curl --fail --retry 2 -X POST http://hmpps-person-match/jobs/recordcountreport
