nomis-oauth:
  base-url: https://sign-in-dev.hmpps.service.justice.gov.uk

offender-search:
  base-url: https://probation-offender-search-dev.hmpps.service.justice.gov.uk

prisoner-search:
  base-url: https://prisoner-search-dev.prison.service.justice.gov.uk

domain-event-and-delius-api:
  base_url: https://domain-events-and-delius-dev.hmpps.service.justice.gov.uk

prison-service:
  base-url: https://prison-api-dev.prison.service.justice.gov.uk

feature:
  flags:
    enable-hmcts-sqs: true
    enable-delius-search: true
    enable-nomis-search: true
    enable-delius-domain-event-sqs: true

