nomis-oauth:
  base-url: https://sign-in.hmpps.service.justice.gov.uk

offender-search:
  base-url: https://probation-offender-search.hmpps.service.justice.gov.uk

prisoner-search:
  base-url: https://prisoner-search.prison.service.justice.gov.uk

domain_event_and_delius_api:
  base_url: https://domain-events-and-delius.hmpps.service.justice.gov.uk
