nomis-oauth:
  base-url: https://sign-in-preprod.hmpps.service.justice.gov.uk

offender-search:
  base-url: https://probation-offender-search-preprod.hmpps.service.justice.gov.uk

prisoner-search:
  base-url: https://prisoner-search-preprod.prison.service.justice.gov.uk