package uk.gov.justice.digital.hmpps.personrecord.model.types.nationality

val LIBRA_NATIONALITY_MAPPINGS: Map<String, NationalityCode> = mapOf(
  "AFGHAN" to NationalityCode.AFGA,
  "ALBANIAN" to NationalityCode.ALBA,
  "ALGERIAN" to NationalityCode.ALGE,
  "UNITED STATES CITIZEN" to NationalityCode.AMER,
  "ANDORRAN" to NationalityCode.ANDO,
  "ANGOLAN" to NationalityCode.ANGOL,
  "CITIZEN OF ANTIGUA AND BARBUDA" to NationalityCode.ANTIG,
  "ARGENTINIAN" to NationalityCode.ARGEN,
  "ARMENIAN" to NationalityCode.ARME,
  "AUSTRALIAN" to NationalityCode.AUSI,
  "AUSTRIAN" to NationalityCode.AUST,
  "AZERBAIJANI" to NationalityCode.AZERB,
  "BAHAMIAN" to NationalityCode.BAHA,
  "BAHRAINI" to NationalityCode.BAHR,
  "BANGLADESHI" to NationalityCode.BANGL,
  "BARBADIAN" to NationalityCode.BARB,
  "BELARUSIAN" to NationalityCode.BELA,
  "BELGIAN" to NationalityCode.BELG,
  "CITIZEN OF BELIZE" to NationalityCode.BELI,
  "BENINESE" to NationalityCode.BENI,
  "BHUTANESE" to NationalityCode.BHUT,
  "BOLIVIAN" to NationalityCode.BOLI,
  "CITIZEN OF BOSNIA AND HERZEGOVINA" to NationalityCode.BOSNI,
  "CITIZEN OF BOTSWANA" to NationalityCode.MOTS,
  "BRAZILIAN" to NationalityCode.BRAZ,
  "BRITISH" to NationalityCode.BRIT,
  "CITIZEN OF BRUNEI" to NationalityCode.BRUN,
  "BULGARIAN" to NationalityCode.BULG,
  "BURKINABE;BURKINAN" to NationalityCode.HV,
  "CITIZEN OF MYANMAR" to NationalityCode.BURM,
  "CITIZEN OF BURUNDI" to NationalityCode.BURU,
  "CAMBODIAN" to NationalityCode.CAMB,
  "CAMEROONIAN" to NationalityCode.CAMER,
  "CANADIAN" to NationalityCode.CANA,
  "CAPE VERDEAN" to NationalityCode.CAVER,
  "CITIZEN OF THE CENTRAL AFRICAN REPUBLIC" to NationalityCode.CF,
  "CHADIAN" to NationalityCode.CHAD,
  "CHILEAN" to NationalityCode.CHIL,
  "CHINESE" to NationalityCode.CHINA,
  "CITIZEN OF GUINEA-BISSAU" to NationalityCode.CGB,
  "CITIZEN OF THE DOMINICAN REPUBLIC" to NationalityCode.CDR,
  "COLOMBIAN" to NationalityCode.COLO,
  "COMORAN" to NationalityCode.COMO,
  "CITIZEN OF THE DEMOCRATIC REPUBLIC OF THE CONGO" to NationalityCode.COND,
  "CITIZEN OF THE REPUBLIC OF THE CONGO" to NationalityCode.CONR,
  "COSTA RICAN" to NationalityCode.COSRI,
  "CROATIAN" to NationalityCode.CROAT,
  "CUBAN" to NationalityCode.CUBA,
  "CYPRIOT" to NationalityCode.CYPR,
  "CZECH" to NationalityCode.CZEC,
  "DANE" to NationalityCode.DANE,
  "DJIBOUTIAN" to NationalityCode.DJIB,
  "DOMINICAN" to NationalityCode.DOMI,
  "DUTCH CITIZEN;DUTCHMAN;DUTCHWOMAN" to NationalityCode.DUTCH,
  "EAST TIMORESE" to NationalityCode.EATIM,
  "ECUADOREAN" to NationalityCode.ECUA,
  "EGYPTIAN" to NationalityCode.EGYP,
  "CITIZEN OF THE UNITED ARAB EMIRATES" to NationalityCode.EMIR,
  "EQUATORIAL GUINEAN" to NationalityCode.EQUATO,
  "ERITREAN" to NationalityCode.ERI,
  "ESTONIAN" to NationalityCode.ESTO,
  "ETHIOPIAN" to NationalityCode.ETHI,
  "CITIZEN OF FIJI" to NationalityCode.FIJI,
  "FILIPINO;FILIPINA" to NationalityCode.FILIP,
  "FINN" to NationalityCode.FINN,
  "FRENCH CITIZEN;FRENCHMAN;FRENCHWOMAN" to NationalityCode.FREN,
  "GABONESE" to NationalityCode.GABO,
  "GAMBIAN" to NationalityCode.GAMB,
  "GEORGIAN" to NationalityCode.GE,
  "GERMAN" to NationalityCode.GERM,
  "GHANAIAN" to NationalityCode.GHAN,
  "GREEK" to NationalityCode.GREE,
  "GRENADIAN" to NationalityCode.GREN,
  "GUATEMALAN" to NationalityCode.GUAT,
  "GUINEAN" to NationalityCode.GUIN,
  "GUYANESE" to NationalityCode.GUYA,
  "HAITIAN" to NationalityCode.HAIT,
  "HONDURAN" to NationalityCode.HOND,
  "HUNGARIAN" to NationalityCode.HUNG,
  "ICELANDER" to NationalityCode.ICE,
  "CITIZEN OF KIRIBATI" to NationalityCode.CT,
  "INDIAN" to NationalityCode.INDI,
  "INDONESIAN" to NationalityCode.INDO,
  "IRANIAN" to NationalityCode.IRAN,
  "IRAQI" to NationalityCode.IRAQ,
  "IRISH" to NationalityCode.IRISH,
  "ISRAELI" to NationalityCode.ISRA,
  "ITALIAN" to NationalityCode.ITAL,
  "CITIZEN OF THE IVORY COAST" to NationalityCode.IVOR,
  "JAMAICAN" to NationalityCode.JAM,
  "JAPANESE" to NationalityCode.JAP,
  "JORDANIAN" to NationalityCode.JORD,
  "KAZAKH" to NationalityCode.KAZA,
  "KENYAN" to NationalityCode.KENY,
  "KOSOVAN" to NationalityCode.KOS,
  "KUWAITI" to NationalityCode.KUWA,
  "KYRGYZ" to NationalityCode.KN,
  "LAO" to NationalityCode.LA,
  "LATVIAN" to NationalityCode.LATV,
  "LEBANESE" to NationalityCode.LEBA,
  "LIBERIAN" to NationalityCode.LIBE,
  "LIBYAN" to NationalityCode.LIBY,
  "LIECHTENSTEIN CITIZEN" to NationalityCode.LIEC,
  "LITHUANIAN" to NationalityCode.LITHU,
  "MACEDONIAN" to NationalityCode.MACE,
  "CITIZEN OF MADAGASCAR" to NationalityCode.MG,
  "MALAWIAN" to NationalityCode.MLAW,
  "CITIZEN OF MALAYSIA" to NationalityCode.MALA,
  "MALDIVIAN" to NationalityCode.MALD,
  "MALIAN" to NationalityCode.ML,
  "MALTESE" to NationalityCode.MALT,
  "MARSHALLESE" to NationalityCode.MAR,
  "MAURITANIAN" to NationalityCode.MARI,
  "MAURITIAN" to NationalityCode.MAUR,
  "MEXICAN" to NationalityCode.MEXI,
  "MICRONESIAN" to NationalityCode.MICR,
  "MOLDOVAN" to NationalityCode.MOLD,
  "MONEGASQUE" to NationalityCode.MONA,
  "MONGOLIAN" to NationalityCode.MONGO,
  "MONTENEGRIN" to NationalityCode.MNE,
  "MOROCCAN" to NationalityCode.MORO,
  "CITIZEN OF LESOTHO" to NationalityCode.LS,
  "MOZAMBICAN" to NationalityCode.MOZA,
  "NAMIBIAN" to NationalityCode.NAMI,
  "NAURUAN" to NationalityCode.NAUR,
  "NEPALESE" to NationalityCode.NEPA,
  "NEW ZEALANDER" to NationalityCode.NZEA,
  "NICARAGUAN" to NationalityCode.NICA,
  "NIGERIAN" to NationalityCode.NIGERIA,
  "CITIZEN OF NIGER" to NationalityCode.NIGER,
  "CITIZEN OF VANUATU" to NationalityCode.VY,
  "NORTH KOREAN" to NationalityCode.NKOR,
  "NORWEGIAN" to NationalityCode.NORW,
  "OMANI" to NationalityCode.OMAN,
  "PAKISTANI" to NationalityCode.PAKN,
  "PALAUAN" to NationalityCode.PALA,
  "PANAMANIAN" to NationalityCode.PANA,
  "PAPUA NEW GUINEAN" to NationalityCode.PNGU,
  "PARAGUAYAN" to NationalityCode.PARA,
  "PERUVIAN" to NationalityCode.PERU,
  "POLE" to NationalityCode.POLE,
  "PORTUGUESE" to NationalityCode.PORTU,
  "QATARI" to NationalityCode.QUAT,
  "ROMANIAN" to NationalityCode.ROMA,
  "RUSSIAN" to NationalityCode.RUSS,
  "RWANDAN" to NationalityCode.RWAN,
  "SALVADOREAN" to NationalityCode.SALV,
  "SAMOAN" to NationalityCode.SAMO,
  "CITIZEN OF SAN MARINO" to NationalityCode.SANM,
  "CITIZEN OF SAO TOME AND PRINCIPE" to NationalityCode.STP,
  "SAUDI ARABIAN" to NationalityCode.SAARA,
  "SENEGALESE" to NationalityCode.SENE,
  "CITIZEN OF SEYCHELLES" to NationalityCode.SEYC,
  "SERBIAN" to NationalityCode.SRB,
  "SIERRA LEONEAN" to NationalityCode.SILE,
  "SINGAPOREAN" to NationalityCode.SING,
  "SLOVAK" to NationalityCode.SLOV,
  "SLOVENE" to NationalityCode.SLENE,
  "SOLOMON ISLANDER" to NationalityCode.SOLO,
  "SOMALI" to NationalityCode.SOMA,
  "SOUTH AFRICAN" to NationalityCode.SOAFR,
  "SOUTH KOREAN" to NationalityCode.SKOR,
  "SOUTH SUDANESE" to NationalityCode.SSUDAN,
  "SPANIARD;SPANISH CITIZEN" to NationalityCode.SPAN,
  "CITIZEN OF SRI LANKA" to NationalityCode.SRIL,
  "STATELESS/NO COUNTRY" to NationalityCode.STATE,
  "SUDANESE" to NationalityCode.SUDAN,
  "SWAZI" to NationalityCode.SWAZI,
  "SWEDE" to NationalityCode.SWEDE,
  "SWISS" to NationalityCode.SWIS,
  "SYRIAN" to NationalityCode.SYRI,
  "TAJIK" to NationalityCode.TA,
  "TANZANIAN" to NationalityCode.TANZ,
  "THAI" to NationalityCode.THAI,
  "TOGOLESE" to NationalityCode.TOGO,
  "TONGAN" to NationalityCode.TNGA,
  "TRINIDAD AND TOBAGO CITIZEN" to NationalityCode.TRIN,
  "TUNISIAN" to NationalityCode.TUNI,
  "TURK" to NationalityCode.TURK,
  "TURKMEN" to NationalityCode.TU,
  "TUVALUAN" to NationalityCode.TV,
  "UGANDAN" to NationalityCode.UGAN,
  "UKRAINIAN" to NationalityCode.UKRA,
  "UNKNOWN" to NationalityCode.UNKNOWN,
  "URUGUAYAN" to NationalityCode.URUG,
  "UZBEK" to NationalityCode.UZBE,
  "VATICAN CITIZEN" to NationalityCode.VTC,
  "VENEZUELAN" to NationalityCode.VENE,
  "VIETNAMESE" to NationalityCode.VIET,
  "ZAMBIAN" to NationalityCode.ZAM,
  "ZIMBABWEAN" to NationalityCode.ZIM,
)
