package uk.gov.justice.digital.hmpps.personrecord.model.types.nationality

import org.slf4j.LoggerFactory
import uk.gov.justice.digital.hmpps.personrecord.extensions.nullIfBlank

enum class NationalityCode(val description: String) {
  AB("Aruban"),
  AFGA("Afghan"),
  AG("Anguillan"),
  ALBA("Albanian"),
  ALGE("Algerian"),
  AMER("American"),
  AN("Dutch Antillean"),
  ANDO("Andorran"),
  ANGOL("Angolan"),
  ANTIG("Citizen of Antigua and Barbuda"),
  ARGEN("Argentine"),
  ARME("Armenian"),
  ASM("American Samoan"),
  AUSI("Australian"),
  AUST("Austrian"),
  AZERB("Azerbaijani"),
  BAHA("Bahamian"),
  BAHR("Bahraini"),
  BANGL("Bangladeshi"),
  BARB("Barbadian"),
  BELA("Belarusian"),
  BELG("Belgian"),
  BELI("Belizean"),
  BENI("Beninese"),
  BHUT("Bhutanese"),
  BM("Bermudian"),
  BOLI("Bolivian"),
  BOSNI("Citizen of Bosnia and Herzegovina"),
  BRAZ("Brazilian"),
  BRIT("British"),
  BRUN("Bruneian"),
  BULG("Bulgarian"),
  BURM("Burmese"),
  BURU("Burundian"),
  CAMB("Cambodian"),
  CAMER("Cameroonian"),
  CANA("Canadian"),
  CAVER("Cape Verdean"),
  CCK("Cocos Islander"),
  CDR("Citizen of the Dominican Republic"),
  CF("Central African"),
  CGB("Citizen of Guinea-Bissau"),
  CHAD("Chadian"),
  CHIL("Chilean"),
  CHINA("Chinese"),
  COK("Cook Islander"),
  COLO("Colombian"),
  COMO("Comoran"),
  COND("Congolese (Congo)"),
  CONG("Congolese"),
  CONR("Congolese (DRC)"),
  COSRI("Costa Rican"),
  CROAT("Croatian"),
  CT("Citizen of Kiribati"),
  CUBA("Cuban"),
  CXR("Christmas Islander"),
  CYPR("Cypriot"),
  CZEC("Czech"),
  DANE("Danish"),
  DJIB("Djiboutian"),
  DOMI("Dominican"),
  DUTCH("Dutch"),
  EATIM("East Timorese"),
  ECUA("Ecuadorean"),
  EGYP("Egyptian"),
  EMIR("Emirati"),
  EQUATO("Equatorial Guinean"),
  ERI("Eritrean"),
  ESTO("Estonian"),
  ETHI("Ethiopian"),
  FG("French Guyanese"),
  FIJI("Fijian"),
  FILIP("Filipino"),
  FINN("Finnish"),
  FO("Faroese"),
  FREN("French"),
  GABO("Gabonese"),
  GAMB("Gambian"),
  GE("Georgian"),
  GERM("German"),
  GHAN("Ghanaian"),
  GI("Gibraltarian"),
  GL("Greenlandic"),
  GLP("Guadeloupe"),
  GREE("Greek"),
  GREN("Grenadian"),
  GRN("Guernseyman/Guernseywoman"),
  GU("Guamanian"),
  GUAT("Guatemalan"),
  GUIN("Guinean"),
  GUYA("Guyanese"),
  HAIT("Haitian"),
  HKG("Hong Konger"),
  HOND("Honduran"),
  HUNG("Hungarian"),
  HV("Burkinan"),
  ICE("Icelandic"),
  INDI("Indian"),
  INDO("Indonesian"),
  IRAN("Iranian"),
  IRAQ("Iraqi"),
  IRISH("Irish"),
  ISRA("Israeli"),
  ITAL("Italian"),
  IVOR("Ivorian"),
  JAM("Jamaican"),
  JAP("Japanese"),
  JORD("Jordanian"),
  JSM("Jerseyman/Jerseywoman"),
  KAZA("Kazakh"),
  KENY("Kenyan"),
  KN("Kyrgyz"),
  KOS("Kosovan"),
  KUWA("Kuwaiti"),
  KY("Cayman Islander"),
  LA("Lao"),
  LATV("Latvian"),
  LEBA("Lebanese"),
  LIBE("Liberian"),
  LIBY("Libyan"),
  LIEC("Liechtenstein citizen"),
  LITHU("Lithuanian"),
  LS("Mosotho"),
  LUX("Luxembourger"),
  MAC("Macanese"),
  MACE("Macedonian"),
  MALA("Malaysian"),
  MALD("Maldivian"),
  MALT("Maltese"),
  MAN("Manx"),
  MAR("Marshallese"),
  MARI("Mauritanian"),
  MAUR("Mauritian"),
  MEXI("Mexican"),
  MG("Malagasy"),
  MICR("Micronesian"),
  ML("Malian"),
  MLAW("Malawian"),
  MNE("Montenegrin"),
  MO("Mahoran"),
  MOLD("Moldovan"),
  MONA("Monegasque"),
  MONGO("Mongolian"),
  MORO("Moroccan"),
  MOTS("Botswanan"),
  MOZA("Mozambican"),
  MS("Montserratian"),
  MTQ("Martiniquais"),
  NAMI("Namibian"),
  NAUR("Nauruan"),
  NCL("New Caledonian"),
  NEPA("Nepalese"),
  NFK("Norfolk Islander"),
  NICA("Nicaraguan"),
  NIGER("Nigerien"),
  NIGERIA("Nigerian"),
  NIU("Niuean"),
  NKOR("North Korean"),
  NORW("Norwegian"),
  NZEA("New Zealander"),
  OMAN("Omani"),
  PAKN("Pakistani"),
  PALA("Palauan"),
  PANA("Panamanian"),
  PARA("Paraguayan"),
  PCN("Pitcairn Islander"),
  PERU("Peruvian"),
  PNGU("Papua New Guinean"),
  POLE("Polish"),
  PORTU("Portuguese"),
  PRI("Puerto Rican"),
  PSE("Palestinian"),
  PYF("French Polynesian"),
  QUAT("Qatari"),
  REF("Refused"),
  REU("Reunionese"),
  RID("Ridunian"),
  ROMA("Romanian"),
  RUSS("Russian"),
  RWAN("Rwandan"),
  SAARA("Saudi Arabian"),
  SALV("Salvadorean"),
  SAMO("Samoan"),
  SANM("Sammarinese"),
  SECR("Serb or Croat"),
  SENE("Senegalese"),
  SEYC("Citizen of Seychelles"),
  SH("St Helenian"),
  SILE("Sierra Leonean"),
  SING("Singaporean"),
  SKOR("South Korean"),
  SLENE("Slovenian"),
  SLOV("Slovak"),
  SOAFR("South African"),
  SOLO("Solomon Islander"),
  SOMA("Somali"),
  SPAN("Spanish"),
  SRB("Serbian"),
  SRIL("Sri Lankan"),
  SRK("Sarkee"),
  SSUDAN("South Sudanese"),
  STATE("Stateless"),
  STLU("St Lucian"),
  STP("Sao Tomean"),
  SUDAN("Sudanese"),
  SURIN("Surinamese"),
  SW("Kittian"),
  SWAZI("Swazi"),
  SWEDE("Swedish"),
  SWIS("Swiss"),
  SYRI("Syrian"),
  TA("Tajik"),
  TAIW("Taiwanese"),
  TANZ("Tanzanian"),
  TCI("Turks and Caicos Islander"),
  THAI("Thai"),
  TKL("Tokelauan"),
  TNGA("Tongan"),
  TOGO("Togolese"),
  TRIN("Trinidadian"),
  TRS("Tristanian"),
  TU("Turkmen"),
  TUNI("Tunisian"),
  TURK("Turkish"),
  TV("Tuvaluan"),
  UGAN("Ugandan"),
  UKRA("Ukrainian"),
  UNKNOWN("Unknown"),
  URUG("Uruguayan"),
  UZBE("Uzbek"),
  VC("Vincentian"),
  VENE("Venezuelan"),
  VG("British Virgin Islander"),
  VIET("Vietnamese"),
  VTC("Vatican Citizen"),
  VY("Citizen of Vanuatu"),
  WA("Sahrawi"),
  WAL("Wallisian"),
  YEMIN("Yemeni"),
  ZAM("Zambian"),
  ZIM("Zimbabwean"),
  ;

  companion object {
    private val log = LoggerFactory.getLogger(this::class.java)

    fun fromProbationMapping(code: String?): NationalityCode? = getNationalityOrUnknown(PROBATION_NATIONALITY_MAPPING, code, "probation")

    fun fromPrisonMapping(code: String?): NationalityCode? = getNationalityOrUnknown(PRISON_NATIONALITY_MAPPING, code, "prison")

    fun fromCommonPlatformMapping(code: String?): NationalityCode? = getNationalityOrUnknown(COMMON_PLATFORM_NATIONALITY_MAPPING, code, "common platform")

    private fun getNationalityOrUnknown(nationalityMap: Map<String, NationalityCode>, code: String?, sourceSystem: String): NationalityCode? = code.normalise()?.let { normalisedCode ->
      return try {
        NationalityCode.valueOf(normalisedCode)
      } catch (e: Exception) {
        log.info("Unable to parse nationality code: $code. Attempting to parse against older nationality codes...")
        nationalityMap[normalisedCode] ?: UNKNOWN.also {
          if (normalisedCode != "UNKNOWN") log.info("Unknown nationality code $sourceSystem: $code")
        }
      }
    }

    private fun String?.normalise(): String? = this?.trim().nullIfBlank()?.uppercase()
  }
}
