package uk.gov.justice.digital.hmpps.personrecord.model.types.nationality

val PRISON_NATIONALITY_MAPPING: Map<String, NationalityCode> = mapOf(
  "AFGHAN" to NationalityCode.AFGA,
  "ALBANIAN" to NationalityCode.ALBA,
  "ALGERIAN" to NationalityCode.ALGE,
  "AMERICAN" to NationalityCode.AMER,
  "AMERICAN SAMOAN" to NationalityCode.ASM,
  "ANDORRAN" to NationalityCode.ANDO,
  "ANGOLAN" to NationalityCode.ANGOL,
  "ANGUILLAN" to NationalityCode.AG,
  "CITIZEN OF ANTIGUA AND BARBUDA\t" to NationalityCode.ANTIG,
  "ARGENTINE" to NationalityCode.ARGEN,
  "ARMENIAN" to NationalityCode.ARME,
  "ARUBAN" to NationalityCode.AB,
  "AUSTRALIAN" to NationalityCode.AUSI,
  "AUSTRIAN" to NationalityCode.AUST,
  "AZERBAIJANI" to NationalityCode.AZERB,
  "BAHAMIAN" to NationalityCode.BAHA,
  "BAHRAINI" to NationalityCode.BAHR,
  "BANGLADESHI" to NationalityCode.BANGL,
  "BARBADIAN" to NationalityCode.BARB,
  "BELARUSIAN" to NationalityCode.BELA,
  "BELGIAN" to NationalityCode.BELG,
  "BELIZEAN" to NationalityCode.BELI,
  "BENINESE" to NationalityCode.BENI,
  "BERMUDIAN" to NationalityCode.BM,
  "BHUTANESE" to NationalityCode.BHUT,
  "BOLIVIAN" to NationalityCode.BOLI,
  "CITIZEN OF BOSNIA AND HERZEGOVINA" to NationalityCode.BOSNI,
  "BOTSWANAN" to NationalityCode.MOTS,
  "BRAZILIAN" to NationalityCode.BRAZ,
  "BRITISH" to NationalityCode.BRIT,
  "BRITISH VIRGIN ISLANDER" to NationalityCode.VG,
  "BRUNEIAN" to NationalityCode.BRUN,
  "BULGARIAN" to NationalityCode.BULG,
  "BURKINAN" to NationalityCode.HV,
  "BURMESE" to NationalityCode.BURM,
  "BURUNDIAN" to NationalityCode.BURU,
  "CAMBODIAN" to NationalityCode.CAMB,
  "CAMEROONIAN" to NationalityCode.CAMER,
  "CANADIAN" to NationalityCode.CANA,
  "CAPE VERDEAN" to NationalityCode.CAVER,
  "CAYMAN ISLANDER" to NationalityCode.KY,
  "CENTRAL AFRICAN\t" to NationalityCode.CF,
  "CHADIAN" to NationalityCode.CHAD,
  "CHILEAN" to NationalityCode.CHIL,
  "CHINESE" to NationalityCode.CHINA,
  "CHRISTMAS ISLANDER" to NationalityCode.CXR,
  "CITIZEN OF GUINEA-BISSAU" to NationalityCode.CGB,
  "CITIZEN OF THE DOMINICAN REPUBLIC" to NationalityCode.CDR,
  "COCOS ISLANDER" to NationalityCode.CCK,
  "COLOMBIAN" to NationalityCode.COLO,
  "COMORAN" to NationalityCode.COMO,
  "CONGOLESE (CONGO)" to NationalityCode.COND,
  "CONGOLESE (DRC)" to NationalityCode.CONR,
  "CONGOLESE" to NationalityCode.CONG,
  "COOK ISLANDER" to NationalityCode.COK,
  "COSTA RICAN" to NationalityCode.COSRI,
  "CROATIAN" to NationalityCode.CROAT,
  "CUBAN" to NationalityCode.CUBA,
  "CYPRIOT" to NationalityCode.CYPR,
  "CZECH" to NationalityCode.CZEC,
  "DANISH" to NationalityCode.DANE,
  "DJIBOUTIAN" to NationalityCode.DJIB,
  "DOMINICAN" to NationalityCode.DOMI,
  "DUTCH" to NationalityCode.DUTCH,
  "DUTCH ANTILLEAN" to NationalityCode.AN,
  "EAST TIMORESE" to NationalityCode.EATIM,
  "ECUADOREAN" to NationalityCode.ECUA,
  "EGYPTIAN" to NationalityCode.EGYP,
  "EMIRATI" to NationalityCode.EMIR,
  "EQUATORIAL GUINEAN" to NationalityCode.EQUATO,
  "ERITREAN" to NationalityCode.ERI,
  "ESTONIAN" to NationalityCode.ESTO,
  "ETHIOPIAN" to NationalityCode.ETHI,
  "FAROESE" to NationalityCode.FO,
  "FIJIAN" to NationalityCode.FIJI,
  "FILIPINO" to NationalityCode.FILIP,
  "FINNISH" to NationalityCode.FINN,
  "FRENCH" to NationalityCode.FREN,
  "FRENCH GUYANESE" to NationalityCode.FG,
  "FRENCH POLYNESIAN" to NationalityCode.PYF,
  "GABONESE" to NationalityCode.GABO,
  "GAMBIAN" to NationalityCode.GAMB,
  "GEORGIAN" to NationalityCode.GE,
  "GERMAN" to NationalityCode.GERM,
  "GHANAIAN" to NationalityCode.GHAN,
  "GIBRALTARIAN" to NationalityCode.GI,
  "GREEK" to NationalityCode.GREE,
  "GREENLANDIC" to NationalityCode.GL,
  "GRENADIAN" to NationalityCode.GREN,
  "GUADELOUPE" to NationalityCode.GLP,
  "GUAMANIAN" to NationalityCode.GU,
  "GUATEMALAN" to NationalityCode.GUAT,
  "GUERNSEYMAN/GUERNSEYWOMAN" to NationalityCode.GRN,
  "GUINEAN" to NationalityCode.GUIN,
  "GUYANESE" to NationalityCode.GUYA,
  "HAITIAN" to NationalityCode.HAIT,
  "HONDURAN" to NationalityCode.HOND,
  "HONG KONGER" to NationalityCode.HKG,
  "HUNGARIAN" to NationalityCode.HUNG,
  "ICELANDIC" to NationalityCode.ICE,
  "CITIZEN OF KIRIBATI" to NationalityCode.CT,
  "INDIAN" to NationalityCode.INDI,
  "INDONESIAN" to NationalityCode.INDO,
  "IRANIAN" to NationalityCode.IRAN,
  "IRAQI" to NationalityCode.IRAQ,
  "IRISH" to NationalityCode.IRISH,
  "ISRAELI" to NationalityCode.ISRA,
  "ITALIAN" to NationalityCode.ITAL,
  "IVORIAN" to NationalityCode.IVOR,
  "JAMAICAN" to NationalityCode.JAM,
  "JAPANESE" to NationalityCode.JAP,
  "JERSEYMAN/JERSEYWOMAN" to NationalityCode.JSM,
  "JORDANIAN" to NationalityCode.JORD,
  "KAZAKH" to NationalityCode.KAZA,
  "KENYAN" to NationalityCode.KENY,
  "KITTIAN" to NationalityCode.SW,
  "KOSOVAN" to NationalityCode.KOS,
  "KUWAITI" to NationalityCode.KUWA,
  "KYRGYZ" to NationalityCode.KN,
  "LAO" to NationalityCode.LA,
  "LATVIAN" to NationalityCode.LATV,
  "LEBANESE" to NationalityCode.LEBA,
  "LIBERIAN" to NationalityCode.LIBE,
  "LIBYAN" to NationalityCode.LIBY,
  "LIECHTENSTEIN CITIZEN" to NationalityCode.LIEC,
  "LITHUANIAN" to NationalityCode.LITHU,
  "LUXEMBOURGER" to NationalityCode.LUX,
  "MACANESE" to NationalityCode.MAC,
  "MACEDONIAN" to NationalityCode.MACE,
  "MAHORAN" to NationalityCode.MO,
  "MALAGASY" to NationalityCode.MG,
  "MALAWIAN" to NationalityCode.MLAW,
  "MALAYSIAN" to NationalityCode.MALA,
  "MALDIVIAN" to NationalityCode.MALD,
  "MALIAN" to NationalityCode.ML,
  "MALTESE" to NationalityCode.MALT,
  "MANX" to NationalityCode.MAN,
  "MARSHALLESE" to NationalityCode.MAR,
  "MARTINIQUAIS" to NationalityCode.MTQ,
  "MAURITANIAN" to NationalityCode.MARI,
  "MAURITIAN" to NationalityCode.MAUR,
  "MEXICAN" to NationalityCode.MEXI,
  "MICRONESIAN" to NationalityCode.MICR,
  "MOLDOVAN" to NationalityCode.MOLD,
  "MONEGASQUE" to NationalityCode.MONA,
  "MONGOLIAN" to NationalityCode.MONGO,
  "MONTENEGRIN" to NationalityCode.MNE,
  "MONTSERRATIAN" to NationalityCode.MS,
  "MOROCCAN" to NationalityCode.MORO,
  "MOSOTHO" to NationalityCode.LS,
  "MOZAMBICAN" to NationalityCode.MOZA,
  "NAMIBIAN" to NationalityCode.NAMI,
  "NAURUAN" to NationalityCode.NAUR,
  "NEPALESE" to NationalityCode.NEPA,
  "NEW CALEDONIAN" to NationalityCode.NCL,
  "NEW ZEALANDER" to NationalityCode.NZEA,
  "NICARAGUAN" to NationalityCode.NICA,
  "NIGERIAN" to NationalityCode.NIGERIA,
  "NIGERIEN" to NationalityCode.NIGER,
  "NIUEAN" to NationalityCode.NIU,
  "CITIZEN OF VANUATU" to NationalityCode.VY,
  "NORFOLK ISLANDER" to NationalityCode.NFK,
  "NORTH KOREAN" to NationalityCode.NKOR,
  "NORWEGIAN" to NationalityCode.NORW,
  "OMANI" to NationalityCode.OMAN,
  "PAKISTANI" to NationalityCode.PAKN,
  "PALAUAN" to NationalityCode.PALA,
  "PALESTINIAN" to NationalityCode.PSE,
  "PANAMANIAN" to NationalityCode.PANA,
  "PAPUA NEW GUINEAN" to NationalityCode.PNGU,
  "PARAGUAYAN" to NationalityCode.PARA,
  "PERUVIAN" to NationalityCode.PERU,
  "PITCAIRN ISLANDER" to NationalityCode.PCN,
  "POLISH" to NationalityCode.POLE,
  "PORTUGUESE" to NationalityCode.PORTU,
  "PUERTO RICAN" to NationalityCode.PRI,
  "QATARI" to NationalityCode.QUAT,
  "REFUSED" to NationalityCode.REF,
  "REUNIONESE" to NationalityCode.REU,
  "RIDUNIAN" to NationalityCode.RID,
  "ROMANIAN" to NationalityCode.ROMA,
  "RUSSIAN" to NationalityCode.RUSS,
  "RWANDAN" to NationalityCode.RWAN,
  "SAHRAWI" to NationalityCode.WA,
  "ST HELENIAN" to NationalityCode.SH,
  "ST LUCIAN" to NationalityCode.STLU,
  "SALVADOREAN" to NationalityCode.SALV,
  "SAMOAN" to NationalityCode.SAMO,
  "SAMMARINESE" to NationalityCode.SANM,
  "SAO TOMEAN" to NationalityCode.STP,
  "SARKEE" to NationalityCode.SRK,
  "SAUDI ARABIAN" to NationalityCode.SAARA,
  "SENEGALESE" to NationalityCode.SENE,
  "SERB OR CROAT" to NationalityCode.SECR,
  "CITIZEN OF SEYCHELLES" to NationalityCode.SEYC,
  "SERBIAN" to NationalityCode.SRB,
  "SIERRA LEONEAN" to NationalityCode.SILE,
  "SINGAPOREAN" to NationalityCode.SING,
  "SLOVAK" to NationalityCode.SLOV,
  "SLOVENIAN" to NationalityCode.SLENE,
  "SOLOMON ISLANDER" to NationalityCode.SOLO,
  "SOMALI" to NationalityCode.SOMA,
  "SOUTH AFRICAN" to NationalityCode.SOAFR,
  "SOUTH KOREAN" to NationalityCode.SKOR,
  "SOUTH SUDANESE" to NationalityCode.SSUDAN,
  "SPANISH" to NationalityCode.SPAN,
  "SRI LANKAN" to NationalityCode.SRIL,
  "STATELESS" to NationalityCode.STATE,
  "SUDANESE" to NationalityCode.SUDAN,
  "SURINAMESE" to NationalityCode.SURIN,
  "SWAZI" to NationalityCode.SWAZI,
  "SWEDISH" to NationalityCode.SWEDE,
  "SWISS" to NationalityCode.SWIS,
  "SYRIAN" to NationalityCode.SYRI,
  "TAIWANESE" to NationalityCode.TAIW,
  "TAJIK" to NationalityCode.TA,
  "TANZANIAN" to NationalityCode.TANZ,
  "THAI" to NationalityCode.THAI,
  "TOGOLESE" to NationalityCode.TOGO,
  "TOKELAUAN" to NationalityCode.TKL,
  "TONGAN" to NationalityCode.TNGA,
  "TRINIDADIAN" to NationalityCode.TRIN,
  "TRISTANIAN" to NationalityCode.TRS,
  "TUNISIAN" to NationalityCode.TUNI,
  "TURKISH" to NationalityCode.TURK,
  "TURKMEN" to NationalityCode.TU,
  "TURKS AND CAICOS ISLANDER" to NationalityCode.TCI,
  "TUVALUAN" to NationalityCode.TV,
  "UGANDAN" to NationalityCode.UGAN,
  "UKRAINIAN" to NationalityCode.UKRA,
  "UNKNOWN" to NationalityCode.UNKNOWN,
  "URUGUAYAN" to NationalityCode.URUG,
  "UZBEK" to NationalityCode.UZBE,
  "VATICAN CITIZEN" to NationalityCode.VTC,
  "VENEZUELAN" to NationalityCode.VENE,
  "VIETNAMESE" to NationalityCode.VIET,
  "VINCENTIAN" to NationalityCode.VC,
  "WALLISIAN" to NationalityCode.WAL,
  "YEMENI" to NationalityCode.YEMIN,
  "ZAMBIAN" to NationalityCode.ZAM,
  "ZIMBABWEAN" to NationalityCode.ZIM,
)
