package uk.gov.justice.digital.hmpps.personrecord.service.type
enum class TelemetryEventType(val eventName: String) {
  HMCTS_PROCESSING_FAILURE("CprHMCTSMessageProcessingFailed"),
  DELIUS_MATCH_FOUND("CprNDeliusMatchFound"),
  DELIUS_NO_MATCH_FOUND("CprNDeliusNoMatchFound"),
  DELIUS_PARTIAL_MATCH_FOUND("CprNDeliusPartialMatchFound"),
  DELIUS_PNC_MISMATCH("CprNDeliusPncNoMatchFound"),
  DELIUS_RECORD_CREATION_RECEIVED("CprNDeliusNewRecordReceived"),
  INVALID_PNC("CprHMCTSInvalidPncFound"),
  MISSING_PNC("CprHMCTSPncNotFound"),
  HMCTS_EXACT_MATCH("CprHMCTSRecordExactMatchFound"),
  HMCTS_PARTIAL_MATCH("CprHMCTSRecordPartialMatchFound"),
  HMCTS_RECORD_CREATED("CprHMCTSRecordCreated"),
  HMCTS_MESSAGE_RECEIVED("CprHMCTSMessageReceived"),
  NEW_DELIUS_RECORD_NEW_PNC("CprNDeliusNewRecordCreated"),
  NEW_DELIUS_RECORD_PNC_MATCHED("CprNewNDeliusNewRecordMatchFound"),
  NOMIS_MATCH_FOUND("CprNomisMatchFound"),
  NOMIS_NO_MATCH_FOUND("CprNomisNoMatchFound"),
  NOMIS_PARTIAL_MATCH_FOUND("CprNomisPartialMatchFound"),
  NOMIS_PNC_MISMATCH("CprNomisPncNoMatchFound"),
  VALID_PNC("CprHMCTSValidPnc"),
}
