BEGIN;
-------------------------------------------------------

INSERT INTO nationality_codes(code, description)
VALUES
    ('AFGA', 'Afghan'),
    ('ALBA', 'Albanian'),
    ('ALGE', 'Algerian'),
    ('AMER', 'American'),
    ('ASM', 'American Samoan'),
    ('ANDO', 'Andorran'),
    ('ANGOL', 'Angolan'),
    ('AG', 'Anguillan'),
    ('ANTIG', 'Citizen of Antigua and Barbuda'),
    ('ARGEN', 'Argentine'),
    ('ARME', 'Armenian'),
    ('AB', 'Aruban'),
    ('AUSI', 'Australian'),
    ('AUST', 'Austrian'),
    ('AZERB', 'Azerbaijani'),
    ('BAHA', 'Bahamian'),
    ('BAHR', 'Bahraini'),
    ('BANGL', 'Bangladeshi'),
    ('BARB', 'Barbadian'),
    ('BELA', 'Belarusian'),
    ('BELG', 'Belgian'),
    ('BELI', 'Belizean'),
    ('BENI', 'Beninese'),
    ('BM', 'Bermudian'),
    ('BHUT', 'Bhutanese'),
    ('BOLI', 'Bolivian'),
    ('BOSNI', 'Citizen of Bosnia and Herzegovina'),
    ('MOTS', 'Botswanan'),
    ('BRAZ', 'Brazilian'),
    ('BRIT', 'British'),
    ('VG', 'British Virgin Islander'),
    ('BRUN', 'Bruneian'),
    ('BULG', 'Bulgarian'),
    ('HV', 'Burkinan'),
    ('BURM', 'Burmese'),
    ('BURU', 'Burundian'),
    ('CAMB', 'Cambodian'),
    ('CAMER', 'Cameroonian'),
    ('CANA', 'Canadian'),
    ('CAVER', 'Cape Verdean'),
    ('KY', 'Cayman Islander'),
    ('CF', 'Central African'),
    ('CHAD', 'Chadian'),
    ('CHIL', 'Chilean'),
    ('CHINA', 'Chinese'),
    ('CXR', 'Christmas Islander'),
    ('CGB', 'Citizen of Guinea-Bissau'),
    ('CDR', 'Citizen of the Dominican Republic'),
    ('CCK', 'Cocos Islander'),
    ('COLO', 'Colombian'),
    ('COMO', 'Comoran'),
    ('COND', 'Congolese (Congo)'),
    ('CONR', 'Congolese (DRC)'),
    ('CONG', 'Congolese'),
    ('COK', 'Cook Islander'),
    ('COSRI', 'Costa Rican'),
    ('CROAT', 'Croatian'),
    ('CUBA', 'Cuban'),
    ('CYPR', 'Cypriot'),
    ('CZEC', 'Czech'),
    ('DANE', 'Danish'),
    ('DJIB', 'Djiboutian'),
    ('DOMI', 'Dominican'),
    ('DUTCH', 'Dutch'),
    ('AN', 'Dutch Antillean'),
    ('EATIM', 'East Timorese'),
    ('ECUA', 'Ecuadorean'),
    ('EGYP', 'Egyptian'),
    ('EMIR', 'Emirati'),
    ('EQUATO', 'Equatorial Guinean'),
    ('ERI', 'Eritrean'),
    ('ESTO', 'Estonian'),
    ('ETHI', 'Ethiopian'),
    ('FO', 'Faroese'),
    ('FIJI', 'Fijian'),
    ('FILIP', 'Filipino'),
    ('FINN', 'Finnish'),
    ('FREN', 'French'),
    ('FG', 'French Guyanese'),
    ('PYF', 'French Polynesian'),
    ('GABO', 'Gabonese'),
    ('GAMB', 'Gambian'),
    ('GE', 'Georgian'),
    ('GERM', 'German'),
    ('GHAN', 'Ghanaian'),
    ('GI', 'Gibraltarian'),
    ('GREE', 'Greek'),
    ('GL', 'Greenlandic'),
    ('GREN', 'Grenadian'),
    ('GLP', 'Guadeloupe'),
    ('GU', 'Guamanian'),
    ('GUAT', 'Guatemalan'),
    ('GRN', 'Guernseyman/Guernseywoman'),
    ('GUIN', 'Guinean'),
    ('GUYA', 'Guyanese'),
    ('HAIT', 'Haitian'),
    ('HOND', 'Honduran'),
    ('HKG', 'Hong Konger'),
    ('HUNG', 'Hungarian'),
    ('ICE', 'Icelandic'),
    ('CT', 'Citizen of Kiribati'),
    ('INDI', 'Indian'),
    ('INDO', 'Indonesian'),
    ('IRAN', 'Iranian'),
    ('IRAQ', 'Iraqi'),
    ('IRISH', 'Irish'),
    ('ISRA', 'Israeli'),
    ('ITAL', 'Italian'),
    ('IVOR', 'Ivorian'),
    ('JAM', 'Jamaican'),
    ('JAP', 'Japanese'),
    ('JSM', 'Jerseyman/Jerseywoman'),
    ('JORD', 'Jordanian'),
    ('KAZA', 'Kazakh'),
    ('KENY', 'Kenyan'),
    ('SW', 'Kittian'),
    ('KOS', 'Kosovan'),
    ('KUWA', 'Kuwaiti'),
    ('KN', 'Kyrgyz'),
    ('LA', 'Lao'),
    ('LATV', 'Latvian'),
    ('LEBA', 'Lebanese'),
    ('LIBE', 'Liberian'),
    ('LIBY', 'Libyan'),
    ('LIEC', 'Liechtenstein citizen'),
    ('LITHU', 'Lithuanian'),
    ('LUX', 'Luxembourger'),
    ('MAC', 'Macanese'),
    ('MACE', 'Macedonian'),
    ('MO', 'Mahoran'),
    ('MG', 'Malagasy'),
    ('MLAW', 'Malawian'),
    ('MALA', 'Malaysian'),
    ('MALD', 'Maldivian'),
    ('ML', 'Malian'),
    ('MALT', 'Maltese'),
    ('MAN', 'Manx'),
    ('MAR', 'Marshallese'),
    ('MTQ', 'Martiniquais'),
    ('MARI', 'Mauritanian'),
    ('MAUR', 'Mauritian'),
    ('MEXI', 'Mexican'),
    ('MICR', 'Micronesian'),
    ('MOLD', 'Moldovan'),
    ('MONA', 'Monegasque'),
    ('MONGO', 'Mongolian'),
    ('MNE', 'Montenegrin'),
    ('MS', 'Montserratian'),
    ('MORO', 'Moroccan'),
    ('LS', 'Mosotho'),
    ('MOZA', 'Mozambican'),
    ('NAMI', 'Namibian'),
    ('NAUR', 'Nauruan'),
    ('NEPA', 'Nepalese'),
    ('NCL', 'New Caledonian'),
    ('NZEA', 'New Zealander'),
    ('NICA', 'Nicaraguan'),
    ('NIGERIA', 'Nigerian'),
    ('NIGER', 'Nigerien'),
    ('NIU', 'Niuean'),
    ('VY', 'Citizen of Vanuatu'),
    ('NFK', 'Norfolk Islander'),
    ('NKOR', 'North Korean'),
    ('NORW', 'Norwegian'),
    ('OMAN', 'Omani'),
    ('PAKN', 'Pakistani'),
    ('PALA', 'Palauan'),
    ('PSE', 'Palestinian'),
    ('PANA', 'Panamanian'),
    ('PNGU', 'Papua New Guinean'),
    ('PARA', 'Paraguayan'),
    ('PERU', 'Peruvian'),
    ('PCN', 'Pitcairn Islander'),
    ('POLE', 'Polish'),
    ('PORTU', 'Portuguese'),
    ('PRI', 'Puerto Rican'),
    ('QUAT', 'Qatari'),
    ('REF', 'Refused'),
    ('REU', 'Reunionese'),
    ('RID', 'Ridunian'),
    ('ROMA', 'Romanian'),
    ('RUSS', 'Russian'),
    ('RWAN', 'Rwandan'),
    ('WA', 'Sahrawi'),
    ('SH', 'St Helenian'),
    ('STLU', 'St Lucian'),
    ('SALV', 'Salvadorean'),
    ('SAMO', 'Samoan'),
    ('SANM', 'Sammarinese'),
    ('STP', 'Sao Tomean'),
    ('SRK', 'Sarkee'),
    ('SAARA', 'Saudi Arabian'),
    ('SENE', 'Senegalese'),
    ('SECR', 'Serb or Croat'),
    ('SEYC', 'Citizen of Seychelles'),
    ('SRB', 'Serbian'),
    ('SILE', 'Sierra Leonean'),
    ('SING', 'Singaporean'),
    ('SLOV', 'Slovak'),
    ('SLENE', 'Slovenian'),
    ('SOLO', 'Solomon Islander'),
    ('SOMA', 'Somali'),
    ('SOAFR', 'South African'),
    ('SKOR', 'South Korean'),
    ('SSUDAN', 'South Sudanese'),
    ('SPAN', 'Spanish'),
    ('SRIL', 'Sri Lankan'),
    ('STATE', 'Stateless'),
    ('SUDAN', 'Sudanese'),
    ('SURIN', 'Surinamese'),
    ('SWAZI', 'Swazi'),
    ('SWEDE', 'Swedish'),
    ('SWIS', 'Swiss'),
    ('SYRI', 'Syrian'),
    ('TAIW', 'Taiwanese'),
    ('TA', 'Tajik'),
    ('TANZ', 'Tanzanian'),
    ('THAI', 'Thai'),
    ('TOGO', 'Togolese'),
    ('TKL', 'Tokelauan'),
    ('TNGA', 'Tongan'),
    ('TRIN', 'Trinidadian'),
    ('TRS', 'Tristanian'),
    ('TUNI', 'Tunisian'),
    ('TURK', 'Turkish'),
    ('TU', 'Turkmen'),
    ('TCI', 'Turks and Caicos Islander'),
    ('TV', 'Tuvaluan'),
    ('UGAN', 'Ugandan'),
    ('UKRA', 'Ukrainian'),
    ('UNKNOWN', 'Unknown'),
    ('URUG', 'Uruguayan'),
    ('UZBE', 'Uzbek'),
    ('VTC', 'Vatican Citizen'),
    ('VENE', 'Venezuelan'),
    ('VIET', 'Vietnamese'),
    ('VC', 'Vincentian'),
    ('WAL', 'Wallisian'),
    ('YEMIN', 'Yemeni'),
    ('ZAM', 'Zambian'),
    ('ZIM', 'Zimbabwean')
;

-----------------------------------------------------
COMMIT;