environments {
  dev {
    baseUrl = "https://hmpps-person-record-dev.hmpps.service.justice.gov.uk"
    tokenUrl = "https://sign-in-dev.hmpps.service.justice.gov.uk/auth/oauth/token"
  }
}
endpoint {
  getPrisoner = "/person/prison/#{prison_number}"
  getCrn = "/person/probation/#{crn}"
  getDefendantId = "/person/commonplatform/#{defendant_id}"
}
