profiles {
  local {
    getPrisonNumberUsers = 1
    getCrnUsers = 1
    getDefendantIdUsers = 1
    ramp = 1
    duration = 5
  }
  smoke {
    getPrisonNumberUsers = 30
    getCrnUsers = 1
    getDefendantIdUsers = 1
    ramp = 20
    duration = 360
  }
  happypath {
    getPrisonNumberUsers = 15
    getCrnUsers = 1
    getDefendantIdUsers = 1
    ramp = 20
    duration = 360
  }

}