name: Deploy and publish metrics

on:
  workflow_call:
    inputs:
      app_version:
        description: App version
        required: true
        type: string
      environment:
        description: Environment
        required: true
        type: string
      slack_notification:
        description: Slack notification
        default: "false"
        required: false
        type: string

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@7fb82c71087c04bf9416cf8e91902bde045c878c # v2.22.2
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      app_version: ${{ inputs.app_version }}
      slack_notification: ${{ inputs.slack_notification }}
  record_deployment:
    name: Record deployment
    needs:
      - deploy
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/pact_record_deployment.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      app_version: ${{ inputs.app_version }}