name: Deploy and publish metrics

on:
  workflow_call:
    inputs:
      app_version:
        description: App version
        required: true
        type: string
      environment:
        description: Environment
        required: true
        type: string
      slack_notification:
        description: Slack notification
        default: "false"
        required: false
        type: string
    secrets:
      PLANDEK_CLIENT_KEY:
        required: true
      PLANDEK_TOKEN:
        required: true
      PLANDEK_DEPLOYMENT_URL:
        required: true

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@be0bda171344a1d3bd92fc8ce945a0204cbac33b # v2.14.10
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      app_version: ${{ inputs.app_version }}
      slack_notification: ${{ inputs.slack_notification }}

  publish_deployment_metrics:
    name: Publish deployment metrics to Plandek
    if: always()
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Publish deployment metrics
        uses: ./.github/actions/plandek_deployment
        with:
          plandek_client_key: ${{ secrets.PLANDEK_CLIENT_KEY }}
          plandek_token: ${{ secrets.PLANDEK_TOKEN }}
          plandek_deployment_url: ${{ secrets.PLANDEK_DEPLOYMENT_URL }}
          app_version: ${{ inputs.app_version }}
          repository_name: ${{ github.repository }}
          deployment_status: ${{ needs.deploy.result }}
          commit_sha: ${{ github.sha }}
          build_number: ${{ inputs.app_version }}
          environment_name: ${{ inputs.environment }}