name: Pact Provider Verification
run-name: Pact verify - ${{ github.ref_name || 'manual' }}

on:
  workflow_dispatch:
    inputs:
      consumerName:
        required: false
        description: Consumer name from broker webhook payload
        type: string
      consumerBranch:
        required: false
        description: Consumer branch from broker webhook payload
        type: string
      publishResults:
        required: false
        description: Publish verification results to broker
        type: boolean
        default: true
      providerAppVersion:
        required: false
        description: Application version
        type: string
        default: ''
  workflow_call:
    inputs:
      consumerName:
        required: false
        description: Consumer name from broker webhook payload
        type: string
      consumerBranch:
        required: false
        description: Consumer branch from broker webhook payload
        type: string
      publishResults:
        required: false
        description: Publish verification results to broker
        type: boolean
        default: true
      providerAppVersion:
        required: true
        description: Application version
        type: string

permissions:
  contents: read

concurrency:
  group: pact-provider-verification-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  pact-verify:
    name: Verify provider pacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Check if pact is pre-verified
        id: can-i-deploy
        if: inputs.consumerName && inputs.consumerBranch
        run: |
          if pact-broker can-i-deploy \
            --consumer-name="${{ inputs.consumerName }}" \
            --consumer-version="${{ inputs.consumerBranch }}" \
            --broker-base-url="${{ secrets.PACT_BROKER_URL }}" \
            --broker-username="${{ secrets.HMPPS_PACT_BROKER_USERNAME }}" \
            --broker-password="${{ secrets.HMPPS_PACT_BROKER_PASSWORD }}"; then
            echo "pre_verified=0" >> "$GITHUB_OUTPUT"
            echo "status=Pact already verified for ${{ inputs.consumerName }}@${{ inputs.consumerBranch }}" >> "$GITHUB_OUTPUT"
          else
            echo "pre_verified=1" >> "$GITHUB_OUTPUT"
            echo "status=Pact needs verification for ${{ inputs.consumerName }}@${{ inputs.consumerBranch }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup Java
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: temurin
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

      - name: Start Containers
        if: "!inputs.consumerName || !inputs.consumerBranch || steps.can-i-deploy.outputs.pre_verified != '0'"
        run: make e2e-start-containers

      - name: Verify pacts
        if: "!inputs.consumerName || !inputs.consumerBranch || steps.can-i-deploy.outputs.pre_verified != '0'"
        run: ./gradlew pactTest --console=plain
        env:
          PACT_PUBLISH_RESULTS: ${{ inputs.publishResults }}
          PACT_BROKER_URL: ${{ secrets.PACT_BROKER_URL }}
          PACT_BROKER_USERNAME: ${{ secrets.HMPPS_PACT_BROKER_USERNAME }}
          PACT_BROKER_PASSWORD: ${{ secrets.HMPPS_PACT_BROKER_PASSWORD }}
          GITHUB_BRANCH: ${{ github.ref_name }}
          PACT_CONSUMER_NAME: ${{ inputs.consumerName }}
          PACT_CONSUMER_BRANCH: ${{ inputs.consumerBranch }}
          PACT_PROVIDER_APP_VERSION: ${{ inputs.providerAppVersion }}

      - name: Upload the test artifacts
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: pact-test-results
          path: |
            build/reports/tests
