name: Pipeline [test -> build -> deploy]

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      additional_docker_tag:
        description: Additional docker tag that can be used to specify stable or testing tags
        required: false
        default: ''
        type: string
      push:
        description: Push docker image to registry flag
        required: true
        default: false
        type: boolean
      java_options:
        type: string
        default: '-Xmx4096m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dorg.gradle.daemon=true -Dkotlin.compiler.execution.strategy=in-process -Dorg.gradle.workers.max=1'
        required: false
        description: Setting up common java options
permissions:
  contents: read
  packages: write

concurrency:
  # Only cancel in progress when on a branch - use SHA on main to ensure uniqueness.
  # This will allow multiple pipelines to run at the same time on main.
  # Note that two pipelines running within a few minutes of each other will cause issues with helm deploying to
  # a namespace, as the second one will not be able to get a lock as a deploy will be in progress.
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  helm_lint:
    strategy:
      matrix:
        environments: ['dev', 'preprod', 'prod']
    name: helm lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_helm_lint.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: ${{ matrix.environments }}
  app_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.app_version.outputs.version }}
    steps:
      - id: app_version
        name: Application version creators
        uses: ministryofjustice/hmpps-github-shared-actions/.github/actions/build-test-and-deploy/create_app_version@6ca6653862e916a9221d915216228aee57717570 # v1.0.1
  gradle_verify:
    name: Validate the kotlin
    uses: ./.github/workflows/gradle_localstack_postgres_verify.yml
    secrets: inherit
    with:
      gradle-command: 'BUILD_NUMBER=${{ needs.app_version.outputs.version}} ./gradlew assemble koverHtmlReport'
      upload-build-artifacts: ${{ github.ref == 'refs/heads/main' }}
      java-options: "${{ inputs.java_options }}"
      java-version: '25'
      postgres-tag: '17.4'
      localstack-tag: '4'
      postgres-username: 'root'
      postgres-password: 'dev'
      localstack-services: 'sqs,sns,s3'
    needs:
      - app_version
  e2e_test:
    runs-on: ubuntu-latest
    name: Run e2e Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@39e147cb9de83bb9910b8ef8bd7fff0ee20fcd6f # v6.0.1
      - name: Run e2e tests
        shell: bash
        run: |
          make e2e-start-containers
          ./gradlew e2eTest
      - name: Upload the test artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: e2e-test-results
          path: |
            build/reports/tests
  build:
    name: Build docker image from hmpps-github-actions
    if: github.ref == 'refs/heads/main'
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@v2 # WORKFLOW_VERSION
    with:
      docker_registry: 'ghcr.io'
      registry_org: 'ministryofjustice'
      additional_docker_tag: ${{ inputs.additional_docker_tag }}
      push: ${{ inputs.push || true }}
      docker_multiplatform: false
      download_build_artifacts: true
    needs: gradle_verify
  database_report:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    name: Generate Database Schema Report
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@39e147cb9de83bb9910b8ef8bd7fff0ee20fcd6f # v6.0.1
      - name: Start Required Services
        run: make start-containers
      - name: Initialise DB
        shell: bash
        run: |
          export JAVA_OPTS="${{ inputs.java_options }}"
          ./gradlew initialiseDatabase
      - uses: ministryofjustice/hmpps-github-shared-actions/.github/actions/database_schema_report@6ca6653862e916a9221d915216228aee57717570 # v1.0.1
        with:
          schema: personrecordservice
  deploy_dev:
    name: Deploy to the development environment
    needs:
      - build
      - helm_lint
      - gradle_verify
      - e2e_test
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: 'dev'
      app_version: '${{ needs.build.outputs.app_version }}'
  deploy_preprod:
    name: Deploy to pre-production environment
    needs:
      - build
      - deploy_dev
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: 'preprod'
      app_version: '${{ needs.build.outputs.app_version }}'
  deploy_prod:
    name: Deploy to production environment
    needs:
      - build
      - deploy_preprod
    uses: ./.github/workflows/deploy_env.yml
    secrets: inherit
    with:
      environment: 'prod'
      app_version: '${{ needs.build.outputs.app_version }}'
      slack_notification: true